### ISSUE TITLE
Problema ao baixar pasta com senha

### ISSUE THREAD

**Issue by crackerbad** [alfablac/odrive#1]
Estou com um problema ao tentar baixar pastas com senha,

Exemplo de pasta: https://bit.ly/2ZCwPcs    Senha: A1000

Erro que Obtenho tanto no linux como no windows.

Windows 7
```
Baixando URL:
https://stievano.sharepoint.com/:f:/s/A1000s/EoJdnAEkh21MkVwG_P4rJ7kB_F19K74LkTH
EnH5QTngSnA?e=daTTTS
Traceback (most recent call last):
  File "odrive.py", line 88, in <module>
    HEADERS_COOKIES = auth_url.headers['Set-Cookie']
  File "C:\Python37\lib\site-packages\requests\structures.py", line 54, in __get
item__
    return self._store[key.lower()][1]
KeyError: 'set-cookie'
```

Linux (ubuntu 18.04)

```
Baixando URL:
https://stievano.sharepoint.com/:f:/s/A1000s/EoJdnAEkh21MkVwG_P4rJ7kB_F19K74LkTHEnH5QTngSnA?e=daTTTS
Traceback (most recent call last):
  File "odrive.py", line 88, in <module>
    HEADERS_COOKIES = auth_url.headers['Set-Cookie']
  File "/usr/local/lib/python3.6/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'set-cookie'
```
Agora com pastas sem senha baixo tranquilamente o script é excepcional.

**Comment by alfablac** [comment]
> Exemplo de pasta: https://bit.ly/2ZCwPcs Senha: A1000

@crackerbad subi umas mudanças. Dá um pull no último commit e dá uma testada. Funcionando aqui do meu lado, confirma aí.
A MS mexeu recentemente, deu uma quebrada em algumas partes do código e diversos links estão recebendo erro 429, acho que eles estão matando algumas contas.

**Comment by crackerbad** [comment]
No Windows funcionou, já no linux deu alguns outros erros.
Apenas em pastas com senha, pasta normal baixou normalmente,
```
Baixando URL:
https://stievano.sharepoint.com/:f:/s/A1000s/EoJdnAEkh21MkVwG_P4rJ7kB_F19K74LkTHEnH5QTngSnA?e=daTTTS
Conteudo protegido por senha, carregando chromedriver
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver': 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "odrive.py", line 74, in <module>
    driver = webdriver.Chrome(CHROMEDRIVER_PATH, options=options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

```

**Comment by alfablac** [comment]
Esse erro já é do script não encontrando o "chromedriver"
Ele é necessário pra rodar porque a validação da senha é feita de forma dinâmica via JS.
Eu já inclui as builds do Windows e Linux no repositório. Coloca no PATH, acredito que vá resolver.

**Comment by crackerbad** [comment]
Consegui resolver, o problema era que tambem tinha que instalar o google chrome no vps e tambem tive que adicionar esse argumento `--no-sandbox` nas options do chromedrive no código pois o chrome estava crashando por não abrir em modo root no linux sem ele.

**Comment by crackerbad** [comment]
Parece que o problema com os links com senhas voltou, esta dando o mesmo erro, tanto em linux como no windows.

**Comment by alfablac** [comment]
Vou revisar esse script.
Muita coisa já surgiu que evitam esses erros com a falta do chromedriver.

**Comment by crackerbad** [comment]
> 

Obrigado, esse script ai é uma mão na roda não conheço nenhum outro igual

**Comment by alfablac** [comment]
vai usar o webdriver-manager pra pegar o chromedriver automaticamente.
só rodar um pip install no requirements.txt e executar o script normalmente como antes

**Comment by crackerbad** [comment]
Eu baixei e consegui usar, a parte do chromedrive ficou boa, porém ainda não esta baixando pastas com senha, da o mesmo erro tanto na versão atualizada quando na antiga.
O erro é o mesmo tanto em linux quanto em windows
```
Baixando URL:
https://stievano-my.sharepoint.com/:f:/g/personal/animes1000_stievano_onmicrosoft_com/EnTPCnDPKKJPszlPlzDvX7sBsMr4CobCos3RnW0k9hggZw?e=qlDeq6
Traceback (most recent call last):
  File "odrive.py", line 102, in <module>
    HEADERS_COOKIES = auth_url.headers['Set-Cookie']
  File "/usr/local/lib/python3.7/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'set-cookie'

```

Pastas sem senha está normal

**Comment by alfablac** [comment]
subi um fix, deve dar

**Comment by crackerbad** [comment]
> subi um fix, deve dar

Eu tentei aqui, ele até iniciou o download, mas todos deram falha instantaneamente no windows, no linux tive alguns problemas relacionados ao chrome drive, mas isso eu vou ver se consigo resolver.

```
DevTools listening on ws://127.0.0.1:61961/devtools/browser/8ed1c24b-591f-4e8c-9fca-a44e589546e8
Usando senha: A1000
Fazendo request para autorização
Primeiro POST para pegar inicio da lista
Pegando próxima página de itens
Gerando lista de itens
Chamando aria2c

07/09 16:59:02 [NOTICE] Downloading 51 item(s)

07/09 16:59:02 [ERROR] CUID#7 - Download aborted. URI=https://stievano-my.sharepoint.com/personal/animes1000_stievano_onmicrosoft_com/_layouts/15/download.aspx?UniqueId=CA8877F5-1F84-40C5-BBB4-6AC311EA0098
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://stievano-my.sharepoint.com/personal/animes1000_stievano_onmicrosoft_com/_layouts/15/download.aspx?UniqueId=CA8877F5-1F84-40C5-BBB4-6AC311EA0098
  -> [HttpSkipResponseCommand.cc:240] errorCode=22 The response status is not successful. status=403

07/09 16:59:02 [NOTICE] Download GID#de4ea86a52cb7673 not complete:

07/09 16:59:02 [ERROR] CUID#8 - Download aborted. URI=https://stievano-my.sharepoint.com/personal/animes1000_stievano_onmicrosoft_com/_layouts/15/download.aspx?UniqueId=7CA9F9BA-DB02-409E-B388-8D655D2989DA
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://stievano-my.sharepoint.com/personal/animes1000_stievano_onmicrosoft_com/_layouts/15/download.aspx?UniqueId=7CA9F9BA-DB02-409E-B388-8D655D2989DA
  -> [HttpSkipResponseCommand.cc:240] errorCode=22 The response status is not successful. status=403

07/09 16:59:02 [NOTICE] Download GID#b86c46455f80d96f not complete:

07/09 16:59:03 [ERROR] CUID#9 - Download aborted. URI=https://stievano-my.sharepoint.com/personal/animes1000_stievano_onmicrosoft_com/_layouts/15/download.aspx?UniqueId=792C0D88-99EC-4D95-B665-1AE4512E99F4
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://stievano-my.sharepoint.com/personal/animes1000_stievano_onmicrosoft_com/_layouts/15/download.aspx?UniqueId=792C0D88-99EC-4D95-B665-1AE4512E99F4
  -> [HttpSkipResponseCommand.cc:240] errorCode=22 The response status is not successful. status=403
```

Esse log ai é utilizando no windows.
